all:
	gcc -Wall -Werror -Wextra -pedantic -fsanitize=leak,address,undefined -g -O0 *.c -o main
run:
	./main


#ou então usar apenas essa linha para compilar e já executar
# 	gcc -Wall -Werror -Wextra -pedantic -fsanitize=leak,address,undefined -g -O0 *.c -o main && ./main.c
